
### "###" used as request to request separater 

# Trip Priview
POST http://localhost:8081/trip/preview
content-type: application/json

{
    "userID": "13",
    "destination": {
        "latitude": 9.033445976774495,
        "longitude": 38.753300679964646

    },
    "pickup": {
        "latitude": 9.03343250636164,
        "longitude": 38.76367465114534
    }
}

